version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports: ["8000:8000"]
    environment:
      - PYTHONUNBUFFERED=1
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports: ["5173:80"]
    depends_on: [api]
